services:
  postgres:
    image: postgres:alpine
    container_name: postgres-idiario
    ports:
      - 15435:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=idiario_development
      - POSTGRES_PASSWORD=pOk3549ml04P

  redis:
    image: redis:alpine
    container_name: redis-idiario
    ports:
      - 6379

  app:
    build: .
    container_name: idiario
    command: ./script/start
    volumes:
      - .:/app
      - box:/box
    ports:
      - 3000
    environment:
      - DATABASE_HOST=postgres
      - REDIS_URL=redis://redis-idiario:6379/0
    depends_on:
      - postgres
      - redis

volumes:
  app:
  box:
  pg_data:

